### PR TITLE
Update requirements file

### PR DESCRIPTION
**Pull request by Spayralbe**
Currently the requirements file pins `delphyne` and all of its subdependencies to a specific version, which gets quickly outdated when newer versions become available.
I would argue it's up to the implementers of the ETL to create the requirements file (preferably via a dependency management tool), and therefore it's better to remove it from the template.

### CODE REVIEW

**Review by alepev — COMMENTED** [review]
Wait, I need to understand what is the advantage of removing this. How would you know which delphyne version to use with which delphyne-template version? Should we tell the user to use the latest delphyne from GitHub no matter what? Actually this relates to a problem I was pondering about in the past weeks, namely that we don't have a system in place to keep track of releases on GitHub (we haven't even created tags so far, for neither delphyne nor delphyne-template).

Current situation: we are updating delphyne-template's code to be in sync with the latest delphyne on GitHub, which is different from what the latest delphyne on PyPI. If one uses delphyne-template without knowing this, it's nearly guaranteed that there will be errors indeed. But I'm not sure how just removing the requirements file helps, unless we also tell the user that they should clone and install delphyne from GitHub instead of PyPI. It also makes things a bit harder (for some people) to set up.

Alternative: 
- delphyne-template's `master` branch is kept in sync with the latest delphyne published on PyPI; we keep requirements.txt and point it to the correct delphyne version
- another `dev` branch is kept in sync with the ongoing delphyne developments on GitHub (basically what we are doing now with delphyne-template's `master`). We write somewhere instructions for people that want to use this absolute latest version (i.e. how to install from a local repo cloned from delphyne, instead of from requirements.txt).

For the other packages, I don't see the problem with removing them from requirements.txt if they are already delphyne's dependencies (by dependency management tool you meant pip right?)

**Comment by blootsvoets** [comment]
Two reasons to provide a requirements:

1. easier to get started with the right dependencies
2. avoids a version mismatch.

For this repository, I think 1. is still a valid use case. If you're worried about dependencies getting out of date you do a combination of the following:

- you could still at least list delphyne in requirements and pip will fetch the sub dependencies from there
- remove the version, so pip fetches the latest version, or
- supply a version range (>=3,<4) so you know the major version is going to be compatible with whatever you're developing.

Then in the readme you can list a method to get started, and to freeze the requirements once you're started. Alternatively, you supply a `setup.py` which lists delphine as a direct dependency.

**Comment by Spayralbe** [comment]
Thanks for sharing your thoughts! I'll try to clarify a bit.

The main issue I have with the current requirements.txt file is that it unnecessarily pins all of delphyne's dependencies to a specific version, whereas the allowed version ranges are already specified in delphyne. For most of these subdependencies you would just like to take the latest allowed release, but there's no point in trying to keep that up to date in this repo. Of course when you are using this template to build an actual ETL, you do want to pin all (sub)dependencies to a specific version, but that is not something we can already do here.

That leaves the dependency of delphyne itself. As github doesn't properly support versioning of template repos, we will have to set our own conventions on how to manage the two. I don't see why the template repo master branch would necessarily have to be compatible with the master branch of delphyne, as long as the template is compatible with the latest delphyne release (not pre-release). That way you make sure that at any time you create a new repo from this template, it is guaranteed to work with whatever happens to be the latest release of delphyne at that time.

However, I can see your point on it being a bit more clear on how to get started, when the delphyne dependency is already stated in a requirements file. Additionally, there is a (small) risk that in the time window between applying the template and installing delphyne, a new delphyne version became available that is incompatible with the template you're using.
Perhaps we can therefore specify the delphyne dependency up to the minor version (e.g. `delphyne == 0.1`)? Whenever something will change in a new version of delphyne that breaks compatibility with this template repo, the delphyne minor version will have to be updated. Micro version changes should not break compatibility with the template.

**Comment by blootsvoets** [comment]
I wasn't aware Delphine wasn't versioned with Github releases -- it should be :-). Having a setup.py for both would also work. Another consideration: add broad version ranges to the `install_requires` `setup.py` section of delphyne:
https://packaging.python.org/discussions/install-requires-vs-requirements/#id5

**Pull request merged**
